# See details here: https://www.serverless.com/framework/docs/providers/aws/guide/serverless.yml/
service: t1-ct
frameworkVersion: '2'
useDotenv: true
variablesResolutionMode: 20210219

provider:
  name: aws
  stage: dev
  region: eu-central-1
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  memorySize: 1024

custom:
  webpack:
    webpackConfig: 'webpack.config.js'
    includeModules: true
    packager: 'yarn'
  jest:
    collectCoverage: true
  dotenv:
    variableExpansion: true
    logging: false
    required:
      env:
        - CTP_PROJECT_KEY
        - CTP_CLIENT_SECRET
        - CTP_CLIENT_ID
        - CTP_AUTH_URL
        - CTP_API_URL
        - CTP_SCOPES
        - CTP_DEPLOY_TYPE
        - CTP_POST_BODY
        - TALON_ONE_ATTRIBUTES_MAPPINGS
        - SKU_TYPE
        - SKU_SEPARATOR
        - LANGUAGE
        - LOGGER_MODE
        - CTP_LINE_ITEM_METADATA_TYPE_BODY
        - CTP_CART_METADATA_TYPE_BODY
        - CTP_CUSTOMER_METADATA_TYPE_BODY
        - VERIFY_PRODUCT_IDENTIFIERS

functions:
  api-extension:
    handler: src/api-extension/aws-index.handler

plugins:
  - serverless-webpack
  - ./src/plugins/build-optimizer.js
  - serverless-dotenv-plugin
  - serverless-jest-plugin
  - ./src/plugins/register-api-extension.js
  - ./src/plugins/migrate-customer-profiles.js
  - ./src/plugins/register-api-types.js
