# this workflow runs on all pull requests.
name: 'Run tests'

on:
  - pull_request
  - push:
    branches:
      - master
      - chore-add-test-workflow*

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout code'
      uses: actions/checkout@v2
    - name: 'Setup node'
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'
    - name: 'Install dependencies'
      run: yarn install
    - name: 'Setup serverless'
      uses: serverless/github-action@2.18.0
    - name: 'Run tests'
      run: yarn test
